In [1]:
import numpy as np

In [3]:
a = np.ndarray([1,2,3,4])

In [4]:
print(a)

[[[[6.93000819e-310 6.93000392e-310 2.17507928e+005 6.93000819e-310]
   [6.93000392e-310 1.41796570e-300 6.93000819e-310 6.93000396e-310]
   [5.60709084e-053 6.93000819e-310 6.93000392e-310 1.34128062e+269]]

  [[6.93000819e-310 6.93000392e-310 2.89853919e-270 6.93000392e-310]
   [6.93000392e-310 2.26306089e-119 6.93000819e-310 6.93000392e-310]
   [9.38104815e+018 6.93000975e-310 6.93000393e-310 1.23255744e+106]]]]
